### ISSUE TITLE
maaaaaaaaaaaaaaa (/ˈɡɑːndi, ˈɡændi/;an lawyer,[3] antiMohandas Karamchand Gandhi (/ˈɡɑːndi, ˈɡændi/;[2] 2 October 1869 – 30 January 1948) was an Indian lawyer,[3] anti-colonial nationalist,[4] and political ethicist,[5] who employed nonviolent resistance to lead the successful campaign for India's independence from British Rule,[6] and in turn inspire movements for civil rights and freedom across the world. The honorific Mahātmā (Sanskrit: "great-souled", "venerable"),[7] first applied to him in 1914 in South Africa,[8] is now used throughout the w-colonial nationalist,[4] and political ethicist,[5] who employed nonviolent resistance to lead the successful campaign for India's independence from British Rule,[6] and in turn inspire movements for civil rights and freedom across the world. The honorific Mahātmā (Sanskrit: "great-souled", "venerable"),[7] first applied to him in 1914 in South Africa,[8] is now used throughout the w

### ISSUE THREAD

**Issue by maheshy007** [heellloTEst/troopr-app#17]
Mohandas Karamchand Gandhi (/ˈɡɑːndi, ˈɡændi/;[2] 2 October 1869 – 30 January 1948) was an Indian lawyer,[3] anti-colonial nationalist,[4] and political ethicist,[5] who employed nonviolent resistance to lead the successful campaign for India's independence from British Rule,[6] and in turn inspire movements for civil rights and freedom across the world. The honorific Mahātmā (Sanskrit: "great-souled", "venerable"),[7] first applied to him in 1914 in South Africa,[8] is now used throughout the w

**Comment by JohnOliver02** [comment]
waiting for final logo from design team

**Comment by maheshy007** [comment]
please see the logo attached

**Comment by maheshy007** [comment]
2134567Mohandas Karamchand Gandhi (/ˈɡɑːndi, ˈɡændi/;[2] 2 October 1869 – 30 January 1948) was an Indian lawyer,[3] anti-colonial nationalist,[4] and political ethicist,[5] who employed nonviolent resistance to lead the successful campaign for India's independence from British Rule,[6] and in turn inspire movements for civil rights and freedom across the world. The honorific Mahātmā (Sanskrit: "great-souled", "venerable"),[7] first applied to him in 1914 in South Africa,[8] is now used throughout the w

**Comment by maheshy007** [comment]
1234567fnfjfew123

**Comment by maheshy007** [comment]
234567890 Mohandas Karamchand Gandhi (/ˈɡɑːndi, ˈɡændi/;[2] 2 October 1869 – 30 January 1948) was an Indian lawyer,[3] anti-colonial nationalist,[4] and political ethicist,[5] who employed nonviolent resistance to lead the successful campaign for India's independence from British Rule,[6] and in turn inspire movements for civil rights and freedom across the world. The honorific Mahātmā (Sanskrit: "great-souled", "venerable"),[7] first applied to him in 1914 in South Africa,[8] is now used throughout the w
